env: "local"
logpath: "./internal/logger/logfiles/test-putlists.log"
db:
   host: "localhost"
   port: "5436"
   username: "david"
   dbname: "document_db_test"
   sslmode: "disable"
grpc:
  port: 4042
  timeout: 10h