env: "local"
port: "8080"
logpath: "./internal/logger/logfiles/test-DMS.log"

auth_client:
  address: "localhost:4040"
  timeout: 10h
  retries_count: 5

user_client:
  address: "localhost:4041"
  timeout: 10h
  retries_count: 5

putlist_client:
  address: "localhost:4042"
  timeout: 10h
  retries_count: 5