env: "local"
logpath: "./internal/logger/logfiles/test-authorization.log"

token_ttl: 1h
grpc:
  port: 4040
  timeout: 10h

user_client:
   address: "localhost:4041"
   timeout: 10h
   retries_count: 5

clients_config: "user"