env: "local"
logpath: "./internal/logger/logfiles/test-users.log"
db:
   host: "localhost"
   port: "5436"
   username: "david"
   dbname: "user_db_test"
   sslmode: "disable"
grpc:
  port: 4041
  timeout: 1h